// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4S7Bjqdcz-sAAwRWVrtzj3RPhrkRcx10',
    appId: '1:36657885045:web:54b701bfb75d7d3fdbed3c',
    messagingSenderId: '36657885045',
    projectId: 'tiki-a9d30',
    authDomain: 'tiki-a9d30.firebaseapp.com',
    storageBucket: 'tiki-a9d30.firebasestorage.app',
    measurementId: 'G-CSRPVJCTF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbAWm9s5DyGEv6LgTM6tUQsJB5Jf_ut5U',
    appId: '1:36657885045:android:332b9d26f8b1ca53dbed3c',
    messagingSenderId: '36657885045',
    projectId: 'tiki-a9d30',
    storageBucket: 'tiki-a9d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Kyv-eYH7Hlum9K1XiijTg_dDrP6kZ4Q',
    appId: '1:36657885045:ios:29c0bbd964befef5dbed3c',
    messagingSenderId: '36657885045',
    projectId: 'tiki-a9d30',
    storageBucket: 'tiki-a9d30.firebasestorage.app',
    iosBundleId: 'com.tiki.mr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Kyv-eYH7Hlum9K1XiijTg_dDrP6kZ4Q',
    appId: '1:36657885045:ios:29c0bbd964befef5dbed3c',
    messagingSenderId: '36657885045',
    projectId: 'tiki-a9d30',
    storageBucket: 'tiki-a9d30.firebasestorage.app',
    iosBundleId: 'com.tiki.mr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4S7Bjqdcz-sAAwRWVrtzj3RPhrkRcx10',
    appId: '1:36657885045:web:a772feb0a0193de5dbed3c',
    messagingSenderId: '36657885045',
    projectId: 'tiki-a9d30',
    authDomain: 'tiki-a9d30.firebaseapp.com',
    storageBucket: 'tiki-a9d30.firebasestorage.app',
    measurementId: 'G-SRVBHSF8YN',
  );
}
